apiVersion: v2
type: application
version: 0.15.0
appVersion: 1.16.0
name: pagopa-ecommerce-watchdog-deadletter-service
description: Microservice designed to support deadletter monitoring for the eCommerce transactions process.
dependencies:
  - name: microservice-chart
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    version: 8.0.0
